### ISSUE TITLE
Random crashing on Everdrive N8 Pro

### ISSUE THREAD

**Issue by Ritaku02** [ShadowOne333/The-Legend-of-Zelda-Redux#10]
Playing on the N8 Pro, when I enter or exit a cave, there's a random chance the game will freeze. This is regardless of any optional patches applied; even only applying the base patch results in this behavior, and both the MMC1 and MMC5 versions suffer from this problem. Playing on an emulator such as Mesen appears to work fine.

I'm on the latest firmware for the Everdrive, and have also tried the unreleased patches on the Code page.

**Comment by ShadowOne333** [comment]
Unfortunately, there's not much I can do on my side.
The hacks have been confirmed to work on true reproduction cartridges with MMC1/MMC5 chips, so the only thing I can suggest here would be to contact the Everdrive developers and mention this hack to them, so that they can hopefully make a firmware update that supports this hack.

Sorry I can't be of more help.
