### ISSUE TITLE
No 3.3.2 Dungeon music patch on 3.3.3?

### ISSUE THREAD

**Issue by Seven7zip** [ShadowOne333/The-Legend-of-Zelda-Redux#19]
Why?

**Comment by ShadowOne333** [comment]
The two Dungeon Music optional patches were missing from the latest pack, a mistake when packing everything up it seems, since the patches were still available in the source code both in code form and IPS form inside the "patches" folder.
I have added them back into the main Releases package, and the one in RHDN has been updated as well, it just has to be approved first.
