### ISSUE TITLE
introduction titles

### ISSUE THREAD

**Issue by spencersmitty** [ShadowOne333/The-Legend-of-Zelda-Redux#22]
hello, thank you for your work ;)

i am curious about the title for the 'magical key' being changed to 'lion key'. i've tried changing it back in the hex editor for purist's sake but something is preventing the indent from operating correctly. could you possibly walk me through what i might be doing wrong, or make a unique ips patch? if not i understand.

<img width="836" alt="1" src="https://github.com/user-attachments/assets/dcdb9765-40cf-4f91-a12a-a01895740e5b">
<img width="780" alt="2" src="https://github.com/user-attachments/assets/862f9ef7-e379-4a69-bc22-b14b515d68b1">

**Comment by ShadowOne333** [comment]
That's because I redid all of the text for the source code of Redux, and I changed the pointers so they get automatically repointed upon compilation.
This is the part you're looking for:
https://github.com/ShadowOne333/The-Legend-of-Zelda-Redux/blob/master/code/text/story.asm#L226-L234

You need to change the `db $15, "  ",{end}` in there to be `db $15, "KEY",{end}` instead in order for the full word to appear properly, otherwise, if you're doing it through Hex editing, you'd have to change both the pointer and move the actual part to an unused area of the bank.

**Comment by spencersmitty** [comment]
thank you for the explanation :-)

closing.

**Comment by spencersmitty** [comment]
thank you for the explanation. closing :p
